XBRL_MAPPINGS = {
    # ── Income Statement ──────────────────────────────────────
    "revenue":                          "Revenue",
    "cogs":                             "CostOfGoodsAndServicesSold",
    "gross_profit":                     "GrossProfit",
    "rd_expense":                       "ResearchAndDevelopmentExpenses",
    "sga_expense":                      "SellingGeneralAndAdminExpenses",
    "marketing_expense":                "MarketingExpenses",
    "depreciation_expense":             "DepreciationExpense",
    "amortization_intangibles":         "AmortizationOfIntangibles",
    "restructuring_expense":            "RestructuringExpenseBenefit",
    "goodwill_impairment":              "GoodwillWriteoffs",
    "other_operating_expense":          "OtherOperatingExpense",
    "total_opex":                       "TotalOperatingExpenses",
    "operating_income":                 "OperatingIncomeLoss",
    "interest_expense":                 "InterestExpense",
    "interest_income":                  "InterestIncome",
    "interest_and_dividend_income":     "InterestAndDividendIncome",
    "nonoperating_income":              "NonoperatingIncomeExpense",
    "pretax_income":                    "PretaxIncomeLoss",
    "tax_expense":                      "IncomeTaxes",
    "net_income":                       "NetIncome",
    "net_income_to_common":             "NetIncomeToCommonShareholders",
    "minority_interest_income":         "MinorityInterestIncomeExpense",
    "profit_loss":                      "ProfitLoss",
    "eps_basic":                        "EarningsPerShareBasic",
    "eps_diluted":                      "EarningsPerShareDiluted",
    "basic_shares":                     "SharesAverage",
    "diluted_shares":                   "SharesFullyDilutedAverage",
    "shares_issued":                    "SharesIssued",
    "shares_year_end":                  "SharesYearEnd",

    # Industry-specific revenue
    "advertising_revenue":              "AdvertisingRevenueIS",
    "subscription_revenue":             "SubscriptionRevenue",
    "licensing_revenue":                "LicensingRevenue",
    "royalty_revenue":                  "RoyaltyRevenue",
    "franchise_revenue":                "FranchiseRevenue",
    "rental_leasing_revenue":           "RentalAndLeasingRevenue",
    "financial_services_revenue":       "FinancialServicesRevenue",
    "technology_services_revenue":      "TechnologyServicesRevenue",
    "health_care_revenue":              "HealthCareRevenue",
    "oil_and_gas_revenue":              "OilAndGasRevenue",
    "electric_utility_revenue":         "ElectricUtilityRevenue",
    "government_contracts_revenue":     "GovernmentContractsRevenue",
    "commissions_revenue":              "CommissionsRevenue",
    "management_fee_revenue":           "ManagementFeeRevenue",
    "product_revenue":                  "ProductRevenue",

    # Industry-specific expenses
    "labor_expenses":                   "LaborExpenses",
    "occupancy_expense":                "OccupancyExpense",
    "communication_tech_expense":       "CommunicationAndTechnologyExpense",
    "professional_fees":                "ProfessionalFees",
    "advertising_expense":              "AdvertisingExpense",
    "finance_lease_expense":            "FinanceLeaseExpense",
    "pension_expense":                  "PensionExpense",
    "asset_impairment":                 "AssetImpairmentChargesIS",

    # Banking/insurance specific income statement
    "net_interest_income":              "NetInterestIncome",
    "net_interest_income_after_prov":   "NetInterestIncomeAfterProvision",
    "non_interest_income":              "NonInterestIncome",
    "non_interest_expense":             "NonInterestExpense",
    "provision_credit_losses":          "ProvisionForCreditLosses",
    "policy_benefits_claims":           "PolicyBenefitsAndClaims",

    # Other income statement
    "gain_loss_dispositions":           "GainLossOnDispositions",
    "gain_loss_investments":            "GainLossOnInvestmentsIS",
    "foreign_currency_gain_loss":       "ForeignCurrencyGainLoss",
    "equity_method_income":             "EquityMethodInvestmentIncome",
    "loss_debt_extinguishment":         "LossOnDebtExtinguishment",
    "discontinued_operations":          "DiscontinuedOperationsIncome",

    # ── Balance Sheet — Current Assets ────────────────────────
    "cash":                             "CashAndMarketableSecurities",
    "cash_and_equivalents":             "CashAndCashEquivalents",
    "restricted_cash_current":          "RestrictedCashCurrent",
    "short_term_investments":           "ShortTermInvestments",
    "accounts_receivable":              "TradeReceivables",
    "accounts_receivable_gross":        "AccountsReceivableGross",
    "allowance_doubtful":               "AllowanceForDoubtfulAccounts",
    "inventory":                        "Inventories",
    "prepaid_expenses":                 "PrepaidExpenses",
    "contract_assets":                  "ContractAssets",
    "income_tax_receivable":            "IncomeTaxReceivable",
    "deferred_tax_current_assets":      "DeferredTaxCurrentAssets",
    "customer_advances":                "CustomerAdvances",
    "assets_held_for_sale":             "AssetsHeldForSale",
    "other_current_assets":             "OtherOperatingCurrentAssets",
    "total_current_assets":             "CurrentAssetsTotal",

    # ── Balance Sheet — Non-Current Assets ────────────────────
    "ppe_gross":                        "GrossPropertyPlantEquipment",
    "ppe_net":                          "PlantPropertyEquipmentNet",
    "accumulated_depreciation":         "AccumulatedDepreciation",
    "goodwill":                         "Goodwill",
    "intangible_assets":                "IntangibleAssets",
    "intangible_assets_gross":          "IntangibleAssetsGross",
    "accumulated_amort_intangibles":    "AccumulatedAmortizationIntangibles",
    "goodwill_and_intangibles":         "GoodwillAndIntangiblesNet",
    "longterm_investments":             "LongtermInvestments",
    "equity_method_investments":        "InvestmentsEquityMethod",
    "operating_lease_rou_asset":        "OperatingLeaseRightOfUseAsset",
    "deferred_tax_noncurrent_assets":   "DeferredTaxNoncurrentAssets",
    "restricted_cash_noncurrent":       "RestrictedCashNonCurrent",
    "deferred_policy_acquisition":      "DeferredPolicyAcquisitionCosts",
    "security_deposits":                "SecurityDepositsAsset",
    "defined_benefit_plan_assets":      "DefinedBenefitPlanAssets",
    "real_estate_investments":          "RealEstateInvestments",
    "regulated_assets":                 "RegulatedAssets",
    "net_loans_and_leases":             "NetLoansAndLeases",
    "notes_receivable_noncurrent":      "NotesReceivableNonCurrent",
    "other_noncurrent_assets":          "OtherOperatingNonCurrentAssets",
    "total_noncurrent_assets":          "NonCurrentAssetsTotal",
    "total_assets":                     "Assets",

    # ── Balance Sheet — Current Liabilities ───────────────────
    "accounts_payable":                 "TradePayables",
    "short_term_debt":                  "ShortTermDebt",
    "current_portion_ltd":              "CurrentPortionOfLongTermDebt",
    "deferred_revenue_current":         "DeferredRevenueCurrent",
    "contract_liabilities":             "ContractLiabilities",
    "taxes_payable":                    "TaxesPayable",
    "accrued_compensation":             "AccruedCompensation",
    "accrued_income_taxes":             "AccruedIncomeTaxes",
    "dividends_payable":                "DividendsPayable",
    "self_insurance_reserve":           "SelfInsuranceReserve",
    "other_current_liabilities":        "OtherOperatingCurrentLiabilities",
    "total_current_liabilities":        "CurrentLiabilitiesTotal",

    # ── Balance Sheet — Non-Current Liabilities ───────────────
    "long_term_debt":                   "LongTermDebt",
    "convertible_debt":                 "ConvertibleDebtNonCurrent",
    "deferred_revenue_noncurrent":      "DeferredRevenueNonCurrent",
    "operating_lease_lt":               "OperatingLeaseNonCurrentDebtEquivalent",
    "deferred_tax_noncurrent_liab":     "DeferredTaxNonCurrentLiabilities",
    "pension_obligations":              "PensionObligations",
    "defined_benefit_obligations":      "DefinedBenefitPlanObligations",
    "deferred_compensation_noncurrent": "DeferredCompensationNonCurrent",
    "regulated_liabilities":            "RegulatedLiabilities",
    "total_deposits":                   "TotalDeposits",
    "other_noncurrent_liabilities":     "OtherOperatingNonCurrentLiabilities",
    "total_noncurrent_liabilities":     "NonCurrentLiabilitiesTotal",
    "total_liabilities":                "Liabilities",

    # ── Balance Sheet — Equity ────────────────────────────────
    "total_equity":                     "CommonEquity",
    "total_equity_incl_minority":       "AllEquityBalanceIncludingMinorityInterest",
    "minority_interest_bs":             "MinorityInterestBalance",
    "preferred_stock":                  "PreferredStock",
    "additional_paid_in_capital":       "AdditionalPaidInCapital",
    "retained_earnings":                "RetainedEarnings",
    "accumulated_oci":                  "AccumulatedOtherComprehensiveIncome",
    "unearned_revenue_equity":          "UnearnedRevenue",
    "total_liabilities_and_equity":     "LiabilitiesAndEquity",

    # ── Cash Flow — Operating ─────────────────────────────────
    "cfo":                              "NetCashFromOperatingActivities",
    "da":                               "DepreciationAmortizationCF",
    "sbc":                              "StockBasedCompensationCF",
    "deferred_tax_cf":                  "DeferredIncomeTaxCF",
    "change_in_receivables":            "ChangeInReceivables",
    "change_in_inventory":              "ChangeInInventory",
    "change_in_payables":               "ChangeInPayables",
    "change_in_deferred_revenue":       "ChangeInDeferredRevenue",
    "change_in_other_wc":               "ChangeInOtherWorkingCapital",
    "change_in_accrued_liab":           "ChangeInAccruedLiabilities",
    "provision_doubtful_cf":            "ProvisionForDoubtfulAccountsCF",
    "gain_loss_asset_sales_cf":         "GainLossOnAssetSalesCF",
    "impairment_charges_cf":            "ImpairmentChargesCF",
    "operating_lease_payments":         "OperatingLeasePayments",
    "finance_lease_payments":           "FinanceLeasePayments",
    "capital_lease_payments_cf":        "CapitalLeasePaymentsCF",
    "other_noncash_cf":                 "OtherNonCashItemsCF",

    # ── Cash Flow — Investing ─────────────────────────────────
    "capex":                            "CapitalExpenses",
    "investment_purchases":             "InvestmentPurchases",
    "investment_proceeds":              "InvestmentProceeds",
    "acquisitions_net":                 "AcquisitionsNet",
    "purchase_intangibles":             "PurchaseOfIntangibleAssets",
    "proceeds_sale_ppe":                "ProceedsFromSaleOfPPE",
    "proceeds_maturities_invest":       "ProceedsFromMaturitiesOfInvestments",
    "divestiture_proceeds":             "DivestitureProceeds",
    "net_cash_investing":               "NetCashFromInvestingActivities",

    # ── Cash Flow — Financing ─────────────────────────────────
    "debt_proceeds":                    "DebtProceeds",
    "debt_repayments":                  "DebtRepayments",
    "stock_repurchase_payments":        "StockRepurchasePayments",
    "stock_issuance_proceeds":          "StockIssuanceProceeds",
    "dividends_paid":                   "CommonDividendsPaid",
    "distributions_minority":           "DistributionsToMinorityInterests",
    "debt_issuance_costs":              "PaymentsOfDebtIssuanceCosts",
    "fx_effect_on_cash":                "ForeignExchangeEffectOnCash",
    "net_cash_financing":               "NetCashFromFinancingActivities",

    # ── Summary ───────────────────────────────────────────────
    "net_change_in_cash":               "NetChangeInCash",

    # ── Forward-Looking Disclosures ───────────────────────────
    "op_lease_commitment_y1":           "OperatingLeaseCommitmentYear1",
    "op_lease_commitment_y2":           "OperatingLeaseCommitmentYear2",
    "op_lease_commitment_y3":           "OperatingLeaseCommitmentYear3",
    "op_lease_commitment_y4":           "OperatingLeaseCommitmentYear4",
    "op_lease_commitment_y5":           "OperatingLeaseCommitmentYear5",
    "op_lease_commitment_thereafter":   "OperatingLeaseCommitmentAfterYear5",
    "intang_amort_forecast_y1":         "ForecastedIntangibleAmortizationYear1",
    "intang_amort_forecast_y2":         "ForecastedIntangibleAmortizationYear2",
    "intang_amort_forecast_y3":         "ForecastedIntangibleAmortizationYear3",
    "intang_amort_forecast_y4":         "ForecastedIntangibleAmortizationYear4",
    "intang_amort_forecast_y5":         "ForecastedIntangibleAmortizationYear5",
    "intang_amort_forecast_thereafter": "ForecastedIntangibleAmortizationAfterYear5",
}