from backend.processing.xbrl_map import XBRL_MAPPINGS

def test_xbrl_mappings_has_minimum_entries():
    assert len(XBRL_MAPPINGS) >= 30

def test_xbrl_mappings_covers_required_fields():
    required = {
        # Income Statement
        "revenue":                          "Revenue",
        "gross_profit":                     "GrossProfit",
        "operating_income":                 "OperatingIncomeLoss",  # EBIT
        "net_income":                       "NetIncome",
        "cogs":                             "CostOfGoodsAndServicesSold",
        "da":                               "DepreciationAmortizationCF",

        # Balance Sheet
        "cash":                             "CashAndMarketableSecurities",
        "accounts_receivable":              "TradeReceivables",
        "accounts_receivable_gross":        "AccountsReceivableGross",
        "inventory":                        "Inventories",
        "accounts_payable":                 "TradePayables",
        "ppe_net":                          "PlantPropertyEquipmentNet",
        "total_equity":                     "CommonEquity",
        "capex":                            "CapitalExpenses",

        # Cash Flow Statement

    }
    for field, concept in required.items():
        assert field in XBRL_MAPPINGS, f"Missing field: {field}"
        assert XBRL_MAPPINGS[field] == concept, (
            f"{field} maps to '{XBRL_MAPPINGS[field]}', expected '{concept}'"
        )


def test_xbrl_mappings_covers_dcf_fields():
    dcf_required = {
        "AccountsReceivableGross",
        "AllowanceForDoubtfulAccounts",
        "CashAndMarketableSecurities",
        "ContractAssets",
        "DeferredTaxCurrentAssets",
        "IncomeTaxReceivable",
        "Inventories",
        "OtherNonOperatingCurrentAssets",
        "OtherNonOperatingNonCurrentAssets",
        "OtherOperatingCurrentAssets",
        "PrepaidExpenses",
        "RestrictedCashCurrent",
        "RetirementRelatedCurrentAssets",
        "ShortTermInvestments",
        "TradeReceivables",
        "AccruedCompensation",
        "AccruedIncomeTaxes",
        "ContractLiabilities",
        "CurrentPortionOfLongTermDebt",
        "CustomerAdvances",
        "DeferredRevenueCurrent",
        "DeferredTaxCurrentLiabilities",
        "DeferredTaxNonCurrentLiabilities",
        "DividendsPayable",
        "OngoingOperatingProvisions(WarrantiesEtc)",
        "OperatingLeaseCurrentDebtEquivalent",
        "OtherNonOperatingCurrentLiabilities",
        "OtherOperatingCurrentLiabilities",
        "RetirementRelatedCurrentLiabilities",
        "RetirementRelatedNonCurrentLiabilities",
        "SelfInsuranceReserve",
        "ShortTermDebt",
        "TaxesPayable",
        "TotalDeposits",
        "TradePayables",
        "UnearnedRevenue",
        "AccumulatedAmortizationIntangibles",
        "AccumulatedDepreciation",
        "AssetsHeldForSale",
        "DeferredPolicyAcquisitionCosts",
        "DeferredTaxNoncurrentAssets",
        "DefinedBenefitPlanAssets",
        "Goodwill",
        "GoodwillAndIntangiblesNet",
        "GrossPropertyPlantEquipment",
        "IntangibleAssets",
        "IntangibleAssetsGross",
        "InvestmentsEquityMethod",
        "LoanLossReserve",
        "LongtermInvestments",
        "NetLoansAndLeases",
        "NotesReceivableNonCurrent",
        "OperatingLeaseRightOfUseAsset",
        "OtherOperatingNonCurrentAssets",
        "PlantPropertyEquipmentNet",
        "RealEstateInvestments",
        "RegulatedAssets",
        "RestrictedCashNonCurrent",
        "RetirementRelatedNonCurrentAssets",
        "SecurityDepositsAsset",
        "AssetRetirementObligations",
        "ConvertibleDebtNonCurrent",
        "DeferredCompensationNonCurrent",
        "DeferredRevenueNonCurrent",
        "DefinedBenefitPlanObligations",
        "DefiniteLivedOperatingProvisions(DecommissioningEtc)",
        "LongTermDebt",
        "NonCurrentLiabilitiesTotal",
        "OperatingLeaseNonCurrentDebtEquivalent",
        "OtherNonOperatingNonCurrentLiabilities",
        "OtherOperatingNonCurrentLiabilities",
        "PensionObligations",
        "RegulatedLiabilities",
        "RestructuringProvisions",
        "AccumulatedOtherComprehensiveIncome",
        "AdditionalPaidInCapital",
        "AllEquityBalance",
        "AllEquityBalanceIncludingMinorityInterest",
        "CommonEquity",
        "MinorityInterestBalance",
        "MinorityInterestBS",
        "PreferredStock",
        "RetainedEarnings",
        "TemporaryAndMezzanineFinancing",
        "TreasuryShares",
        "Assets",
        "CurrentAssetsTotal",
        "CurrentLiabilitiesTotal",
        "Liabilities",
        "LiabilitiesAndEquity",
        "NonCurrentAssetsTotal",
        # Banking Revenue
        "NetInterestIncome",
        "NetInterestIncomeAfterProvision",
        "NonInterestIncome",
        "TotalInterestIncomeOperating",
        # Banking Expenses
        "InterestExpenseDeposits",
        "NonInterestExpense",
        "ProvisionForCreditLosses",
        # Insurance
        "PolicyBenefitsAndClaims",
        # Revenue
        "Revenue",
        "ProductRevenue",
        "AdvertisingRevenueIS",
        "CommissionsRevenue",
        "ElectricUtilityRevenue",
        "FinancialServicesRevenue",
        "FranchiseRevenue",
        "GovernmentContractsRevenue",
        "HealthCareRevenue",
        "LicensingRevenue",
        "ManagementFeeRevenue",
        "OilAndGasRevenue",
        "RentalAndLeasingRevenue",
        "RoyaltyRevenue",
        "SubscriptionRevenue",
        "TechnologyServicesRevenue",
        "TenantReimbursementsRevenue",
        # Cost of Revenue
        "CostOfGoodsAndServicesSold",
        "GrossProfit",
        # Operating Expenses
        "ResearchAndDevelopmentExpenses",
        "SellingGeneralAndAdminExpenses",
        "MarketingExpenses",
        "AdvertisingExpense",
        "LaborExpenses",
        "OccupancyExpense",
        "CommunicationAndTechnologyExpense",
        "ProfessionalFees",
        "DepreciationExpense",
        "AmortizationOfIntangibles",
        "FinanceLeaseExpense",
        "OperatingLeaseExpense",
        "PensionExpense",
        "StockBasedCompensationExpense",
        "RestructuringExpenseBenefit",
        "GoodwillWriteoffs",
        "AssetImpairmentChargesIS",
        "BadDebtExpense",
        "CostsSubtotal",
        "OtherOperatingExpense",
        "TotalOperatingExpenses",
        # Operating Income
        "OperatingIncomeLoss",
        # Non-Operating Items
        "InterestExpense",
        "InterestIncome",
        "InterestAndDividendIncome",
        "NonoperatingIncomeExpense",
        "EquityMethodInvestmentIncome",
        "GainLossOnDispositions",
        "GainLossOnInvestmentsIS",
        "ForeignCurrencyGainLoss",
        "LossOnDebtExtinguishment",
        "OtherIncomeIS",
        "OtherExpenseIS",
        # Income Before Tax
        "PretaxIncomeLoss",
        # Income Tax
        "IncomeTaxes",
        "CurrentIncomeTaxExpense",
        "DeferredIncomeTaxExpense",
        "ValuationAllowanceDTA",
        # Net Income
        "NetIncome",
        "NetIncomeToCommonShareholders",
        "IncomeLossContinuingOperations",
        "DiscontinuedOperationsIncome",
        "MinorityInterestIncomeExpense",
        "ProfitLoss",
        "PreferredDividendExpense",
        "ExtraordinaryItemsIncomeExpense(PostTax)",
        "SpecialItemsIncomeExpense(Pretax)",
        # Operating Activities
        "DepreciationAmortizationCF",
        "StockBasedCompensationCF",
        "DeferredIncomeTaxCF",
        "GainLossOnAssetSalesCF",
        "ImpairmentChargesCF",
        "ProvisionForDoubtfulAccountsCF",
        "OperatingLeasePayments",
        "OtherNonCashItemsCF",
        # Working Capital Changes
        "ChangeInReceivables",
        "ChangeInInventory",
        "ChangeInPayables",
        "ChangeInDeferredRevenue",
        "ChangeInAccruedLiabilities",
        "ChangeInOtherWorkingCapital",
        # Investing Activities
        "CapitalExpenses",
        "InvestmentPurchases",
        "InvestmentProceeds",
        "AcquisitionsNet",
        "PurchaseOfIntangibleAssets",
        "ProceedsFromSaleOfPPE",
        "ProceedsFromMaturitiesOfInvestments",
        "DivestitureProceeds",
        # Financing Activities
        "DebtProceeds",
        "DebtRepayments",
        "StockIssuanceProceeds",
        "StockRepurchasePayments",
        "EquityExpenseIncome(BuybackIssued)",
        "CommonDividendsPaid",
        "DistributionsToMinorityInterests",
        "PaymentsOfDebtIssuanceCosts",
        "CapitalLeasePaymentsCF",
        "FinanceLeasePayments",
        "ForeignExchangeEffectOnCash",
    }
    mapped_values = set(XBRL_MAPPINGS.values())
    missing = dcf_required - mapped_values
    assert not missing, f"Missing DCF fields: {missing}"